[project]
dependencies = []
name = "python_std_logging"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
python_std_logging = { path = ".", editable = true }

[tool.pixi.tasks]
