name: deploy-book

on:
  push:
    branches:
      - main
    paths:
      - notebooks/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    strategy:
      matrix: [py312]
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
#    - name: Set up Python 3.13
#      uses: actions/setup-python@v5
#      with:
#        python-version: '3.13'
#       cache: pip # Implicitly uses requirements.txt for cache key
      
    - name: 
      uses: prefix-dev/setup-pixi@v0.8.8
      with:
        environments: ${{ matrix.environment }}
    - name: Install dependencies
      run: pixi install

    # (optional) Cache your executed notebooks between runs
    # if you have config:
    # execute:
    #   execute_notebooks: cache
#    - name: cache executed notebooks
#      uses: actions/cache@v4
#      with:
#        path: _build/.jupyter_cache
#        key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "_build/html"

    # Deploy the book's HTML to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
